version: "3"

services:
  bot:
    build: ./
    command: "gunicorn -w 9 -b 0.0.0.0:5000 run:app"
    volumes:
      - ./:/usr/src/app
    expose:
      - 5000
    restart: always

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./nginx/config:/etc/nginx/conf.d

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
