version: "3"

services:
  bot:
    build: ./
    command: "gunicorn -w 9 -b 0.0.0.0:5000 run:app"
    #command: "python run.py"
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
    restart: always
