version: "3"

services:
  bot:
    build: ./
    command: "gunicorn -w 9 -b 0.0.0.0:80 run:app"
    #command: "python run.py"
    #command: "twistd -n web --port tcp:80 --wsgi sgriffle.app"
    volumes:
      - ./:/usr/src/app
    ports:
      - 80:80
    restart: always
