version: "3"

services:
  bot:
    build: ./
    command: "gunicorn -w 9 -b 0.0.0.0:80 run:app"
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:80
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - bot
