version: "3"

services:
  bot:
    build: ./
    command: "gunicorn -w 9 -b 0.0.0.0:5000 run:app"
    volumes:
      - ./:/usr/src/app
    expose:
      - 5000
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 1337:443
    depends_on:
      - bot
    volumes:
      - ./nginx/certs:/etc/ssl/private
      - ./nginx/config:/etc/nginx/conf.d
